--- i2c-tools-3.1.0/Makefile.old	2009-01-19 17:11:33.000000000 +0200
+++ i2c-tools-3.1.0/Makefile	2013-10-24 13:50:39.000000000 +0300
@@ -8,7 +8,7 @@
 # (at your option) any later version.
 
 DESTDIR	=
-prefix	= /usr/local
+prefix	= /usr
 bindir	= $(prefix)/bin
 sbindir	= $(prefix)/sbin
 mandir	= $(prefix)/share/man
